BootStrap: docker
From: ubuntu:18.04


%runscript
    TMP=$(tempfile -d .)
    wethr > $TMP
    cat $TMP | cowsay
    rm $TMP
%post
    apt update
    apt install -y npm cowsay
    npm install -g wethr


%environment
	export PATH=/usr/games:$PATH
	export LC_ALL=C

