BootStrap: docker
From: ubuntu:18.04


%runscript
    wethr | lolcat

%post
    echo "Hello from inside the container"
    apt update
    apt install -y npm lolcat
    npm install -g wethr


%environment
	PATH=/usr/games:$PATH
	export LC_ALL=C
