BootStrap: docker
From: ubuntu:18.04


%runscript
    wethr | cowsay
%post
    apt update
    apt install -y npm cowsay
    npm install -g wethr


%environment
	export PATH=/usr/games:$PATH
	export LC_ALL=C

